//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ideas {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class IdeasConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static IdeasConfig defaultInstance = ((IdeasConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new IdeasConfig())));
        
        public static IdeasConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        //[global::System.Configuration.DefaultSettingValueAttribute("server=127.0.0.1; user id=root; password=259187;database=jeugenio25_economia;")]
        [global::System.Configuration.DefaultSettingValueAttribute("server=robb0525.locaweb.com.br; user id=jeuge_MegaTime30; password=9w?98iGw;database=jeugenio25_MegaTime30;")]
        public string MySQL {
            get {
                return ((string)(this["MySQL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server=LOCALHOST\\MSSQLSERVER2014; user id=sa; password=emb159753;database=IdeasPD" +
            "V_debug\r\n")]
        public string MsSQL {
            get {
                return ((string)(this["MsSQL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyDdU9fdB9MY7GuP0fTwkPB8fBDmnGuMkSM")]
        public string GoogleGcmApiKey {
            get {
                return ((string)(this["GoogleGcmApiKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dy4dnal0INg:APA91bEQ5q6sshpPXYcmrdPbDu83uw1AxsvU4sqcUptzNP_WSDx2L-fDMoeBwT7AG9nc1" +
            "sKv6ihQYce5jCPNsUzjWhVLvSd7vSk92wftefhZF8rc4al43HjoN1hZj0Bn8_WiUBHDfvqj")]
        public string GoogleGcmDeviceKey {
            get {
                return ((string)(this["GoogleGcmDeviceKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=#path#PDVClient.mdf;Integrate" +
            "d Security=True;Connect Timeout=30")]
        public string MsSqlLocalDB {
            get {
                return ((string)(this["MsSqlLocalDB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.ideasfor.com.br")]
        public string SmtpHost {
            get {
                return ((string)(this["SmtpHost"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp@ideasfor.com.br")]
        public string SmtpUser {
            get {
                return ((string)(this["SmtpUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp@2018")]
        public string SmtpPassword {
            get {
                return ((string)(this["SmtpPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SmtpSSL {
            get {
                return ((bool)(this["SmtpSSL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public int SmtpPort {
            get {
                return ((int)(this["SmtpPort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("site@ideasfor.com.br")]
        public string SmtpSender {
            get {
                return ((string)(this["SmtpSender"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("682ecee9ace6d963925816479b1277b4")]
        public string SharedKey {
            get {
                return ((string)(this["SharedKey"]));
            }
        }
    }
}
